name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt 

    - name: Run tests
      run: |
        pip install pytest && pytest
